server:
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/appointify
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
